Fixes from feedback document
the-deep/questionnaire-builder pull request #59
Opened 2023-09-26 04:55 UTC by subinasr

## Changes

* Fix minor stylings
* Add questionnaire metadata display

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2023-09-26 05:47 UTC, AdityaKhatri requested changes

2023-09-26 05:47 UTC, AdityaKhatri commented on src/components/ChoiceCollectionSelectInput/index.tsx
> +            ));
When newChoice is updated (not added), chances are the oldOptions might already have that option. Make sure you search and remove that before you add the newChoice(updated choice) in the list.

2023-09-26 05:47 UTC, AdityaKhatri commented on src/views/Home/QuestionnaireItem/index.tsx
> +    );
Add fixme to fetch this from the server

2023-09-26 05:47 UTC, AdityaKhatri commented on src/views/QuestionnaireEdit/IntegerQuestionForm/index.tsx
> +        },
This is not required as this is probably set in the form schema as well.

2023-09-27 12:00 UTC, AdityaKhatri requested changes

2023-09-27 12:00 UTC, AdityaKhatri commented on src/views/About/index.tsx
> +                            <>
Add unique key in each mapped item

2023-09-27 12:00 UTC, AdityaKhatri commented on src/views/Home/QuestionnaireItem/index.tsx
> +                                    <span className={styles.tag}>
Chabi kidhar hai, chabi?

2023-09-27 12:00 UTC, AdityaKhatri commented on src/views/Home/QuestionnaireItem/index.tsx
> +                                <span className={styles.tag}>
Chabi kidhar hai, chabi?

2023-09-27 12:00 UTC, AdityaKhatri commented on src/views/Home/QuestionnaireItem/index.tsx
> +                            value={questionnaireItem.enumeratorSkillsDisplay.map(
Chabi kidhar hai, chabi?

2023-09-27 12:01 UTC, subinasr commented on src/views/Home/QuestionnaireItem/index.tsx
> +                                <span className={styles.tag}>
Idhar lock ich nahi hai, chabi se kyaa karoge?

2023-09-27 12:35 UTC, merged